title: Alyssa Ashmore # your name (or website title) here
logo: "/_DSC0869.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Economics & Computer Science Graduate Seeking Business Intelligence Job 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/alyssa-ashmore/">View My LinkedIn Profile</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
